export const termsTranslations = {
  en: {
    hero: {
      title: "Terms of Service",
      effectiveDate: "Effective Date: November 3, 2025",
      subtitle: "These Terms of Service govern your use of Bodhi Technology Lab's platform and services. By accessing our platform, you agree to these terms."
    },
    
    acceptance: {
      title: "1. Acceptance of Terms",
      text1: "By creating an account or using any Bodhi Technology Lab service, you agree to be bound by these Terms of Service, our Privacy Policy, and any additional guidelines we provide. If you do not agree, please discontinue use immediately.",
      text2: "For white-label temple platforms, additional terms may apply as specified in your service agreement."
    },
    
    eligibility: {
      title: "2. Eligibility",
      text1: "You must be at least 13 years old to use our services. If you are under 18, you must have parental or guardian consent.",
      text2: "By registering, you represent that all information provided is accurate and that you have the authority to bind your organization (if registering on behalf of a temple, monastery, or sangha)."
    },
    
    account: {
      title: "3. Account Responsibilities",
      points: [
        {
          label: "Account Security:",
          text: "You are responsible for maintaining the confidentiality of your login credentials. Notify us immediately of any unauthorized access."
        },
        {
          label: "Accurate Information:",
          text: "Provide truthful and complete information when creating your account and keep it updated."
        },
        {
          label: "One Account Per User:",
          text: "Do not create multiple accounts or share accounts with others."
        },
        {
          label: "Your Actions:",
          text: "You are responsible for all activity that occurs under your account."
        }
      ]
    },
    
    acceptableUse: {
      title: "4. Acceptable Use Policy",
      intro: "Our platform is designed to serve the Dharma and reduce suffering. You agree not to:",
      points: [
        "Violate any laws, regulations, or rights of others",
        "Post harmful, hateful, violent, or sexually explicit content",
        "Harass, threaten, or impersonate others",
        "Distribute spam, malware, or viruses",
        "Scrape, crawl, or reverse-engineer our platform",
        "Attempt to gain unauthorized access to systems or data",
        "Use the platform for commercial purposes unrelated to Buddhist practice or temple operations",
        "Misrepresent teachings or impersonate spiritual teachers without authorization"
      ],
      outro: "Violation of this policy may result in account suspension or termination."
    },
    
    ai: {
      title: "5. AI Agent Usage Guidelines",
      intro: "Our Buddhist AI agents are tools for guidance, not substitutes for qualified teachers or professional advice:",
      points: [
        "AI responses are generated by algorithms and may contain errors or misinterpretations",
        "Do not rely solely on AI agents for medical, legal, or mental health advice",
        "Verify important teachings with qualified human teachers",
        "Respect rate limits and avoid abusive or excessive querying",
        "Do not use AI agents to generate harmful, fraudulent, or misleading content"
      ]
    },
    
    ip: {
      title: "6. Intellectual Property",
      ourContent: {
        label: "Our Content:",
        text: "All platform code, design, branding, AI models, and documentation are owned by Bodhi Technology Lab or our licensors. You may not copy, modify, or distribute our proprietary materials without permission."
      },
      yourContent: {
        label: "Your Content:",
        text: "You retain ownership of content you upload (documents, media, AI training data). By uploading, you grant us a license to process, store, and display your content as necessary to provide our services."
      },
      dharmaTeachings: {
        label: "Dharma Teachings:",
        text: "Traditional Buddhist texts, sutras, and teachings are considered part of the shared heritage of humanity. We respect the lineage holders and attributions of all teachings presented on our platform."
      },
      openSource: {
        label: "Open Source:",
        text: "Some components of our platform may be released under open-source licenses. Those components are governed by their respective license terms."
      }
    },
    
    payment: {
      title: "7. Payment Terms & Donations",
      subscription: {
        label: "Subscription Plans:",
        text: "Pricing is listed on our website. Fees are billed monthly or annually in advance. We reserve the right to change pricing with 30 days' notice."
      },
      donationProcessing: {
        label: "Donation Processing:",
        text: "For temple platforms, we facilitate dana (donations) on your behalf. Processing fees (Stripe, PayPal) are clearly disclosed. Donations are non-refundable unless required by law."
      },
      refunds: {
        label: "Refunds:",
        text: "Subscription fees are generally non-refundable. We may provide pro-rated refunds on a case-by-case basis for cancellations within 14 days of initial purchase."
      },
      taxReceipts: {
        label: "Tax Receipts:",
        text: "For charitable donations to qualifying temples, we help generate tax receipts as required by local law. Consult your tax advisor for deductibility."
      }
    },
    
    termination: {
      title: "8. Termination & Suspension",
      byYou: {
        label: "By You:",
        text: "You may cancel your account at any time through your account settings or by contacting support. Upon cancellation, you will lose access to paid features at the end of your billing period."
      },
      byUs: {
        label: "By Us:",
        text: "We may suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or pose a security risk. We will provide notice when possible, except in cases of severe violations."
      },
      dataRetention: {
        label: "Data Retention:",
        text: "Upon termination, we will retain your data for 30 days to allow recovery, then permanently delete it (except as required by law or our Privacy Policy)."
      }
    },
    
    disclaimers: {
      title: "9. Disclaimers & Limitations",
      asIs: {
        label: "AS-IS Service:",
        text: "Our platform is provided \"as-is\" without warranties of any kind, express or implied. We do not guarantee uninterrupted, error-free, or secure operation."
      },
      noProfessionalAdvice: {
        label: "No Professional Advice:",
        text: "AI agents and platform content are for informational and spiritual guidance purposes only—not legal, medical, financial, or therapeutic advice."
      },
      limitationOfLiability: {
        label: "Limitation of Liability:",
        text: "To the fullest extent permitted by law, Bodhi Technology Lab is not liable for indirect, incidental, or consequential damages. Our total liability shall not exceed the fees you paid in the past 12 months."
      },
      thirdPartyServices: {
        label: "Third-Party Services:",
        text: "We integrate with third-party services (payment processors, AI providers). We are not responsible for their actions, outages, or privacy practices."
      }
    },
    
    indemnification: {
      title: "10. Indemnification",
      text: "You agree to indemnify and hold harmless Bodhi Technology Lab, its affiliates, and partners from any claims, damages, or expenses (including legal fees) arising from your use of the platform, violation of these Terms, or infringement of third-party rights."
    },
    
    disputes: {
      title: "11. Dispute Resolution",
      informal: {
        label: "Informal Resolution:",
        text: "Before filing a legal claim, please contact us at"
      },
      email: "privacy@boddhilab.io",
      informalOutro: "to seek an informal resolution. We commit to good-faith dialogue.",
      arbitration: {
        label: "Arbitration:",
        text: "Any disputes not resolved informally will be settled through binding arbitration under the rules of a recognized arbitration body, rather than in court."
      },
      governingLaw: {
        label: "Governing Law:",
        text: "These Terms are governed by the laws of the jurisdiction where Bodhi Technology Lab is registered, without regard to conflict of law principles."
      }
    },
    
    changes: {
      title: "12. Changes to Terms",
      text: "We may update these Terms from time to time. Material changes will be announced via email and/or a platform notice. Continued use after changes indicates acceptance. If you disagree with changes, you may terminate your account."
    },
    
    miscellaneous: {
      title: "13. Miscellaneous",
      points: [
        {
          label: "Entire Agreement:",
          text: "These Terms, along with our Privacy Policy, constitute the entire agreement between you and Bodhi Technology Lab."
        },
        {
          label: "Severability:",
          text: "If any provision is found invalid, the remaining provisions remain in effect."
        },
        {
          label: "Waiver:",
          text: "Failure to enforce any right or provision does not constitute a waiver of future enforcement."
        },
        {
          label: "Assignment:",
          text: "You may not transfer your rights under these Terms without our consent. We may assign our rights to affiliates or successors."
        }
      ]
    },
    
    contact: {
      title: "Questions About These Terms?",
      subtitle: "If you have questions or need clarification about these Terms of Service, we're here to help.",
      email: "privacy@boddhilab.io",
      company: "Bodhi Technology Lab",
      tagline: "Building technology for awakening, with integrity and transparency"
    },
    
    footer: {
      copyright: "© 2025 Bodhi Technology Lab. Building technology for awakening.",
      career: "Career",
      privacy: "Privacy",
      terms: "Terms"
    }
  },
  
  vi: {
    hero: {
      title: "Điều Khoản Dịch Vụ",
      effectiveDate: "Ngày Có Hiệu Lực: 3 Tháng 11, 2025",
      subtitle: "Các Điều Khoản Dịch Vụ này điều chỉnh việc sử dụng nền tảng và dịch vụ của Bodhi Technology Lab. Bằng cách truy cập nền tảng , bạn đồng ý với các điều khoản này."
    },
    
    acceptance: {
      title: "1. Chấp Nhận Điều Khoản",
      text1: "Bằng cách tạo tài khoản hoặc sử dụng bất kỳ dịch vụ nào của Bodhi Technology Lab, bạn đồng ý bị ràng buộc bởi các Điều Khoản Dịch Vụ này, Chính Sách Bảo Mật  và bất kỳ hướng dẫn bổ sung nào chúng tôi cung cấp. Nếu bạn không đồng ý, vui lòng ngừng sử dụng ngay lập tức.",
      text2: "Đối với các nền tảng chùa chiền nhãn trắng, các điều khoản bổ sung có thể áp dụng như được chỉ định trong thỏa thuận dịch vụ của bạn."
    },
    
    eligibility: {
      title: "2. Điều Kiện Đủ Điều Kiện",
      text1: "Bạn phải ít nhất 13 tuổi để sử dụng dịch vụ . Nếu bạn dưới 18 tuổi, bạn phải có sự đồng ý của cha mẹ hoặc người giám hộ.",
      text2: "Bằng cách đăng ký, bạn cam đoan rằng tất cả thông tin được cung cấp là chính xác và rằng bạn có quyền ràng buộc tổ chức của mình (nếu đăng ký thay mặt cho chùa chiền, tu viện hoặc tăng đoàn)."
    },
    
    account: {
      title: "3. Trách Nhiệm Tài Khoản",
      points: [
        {
          label: "Bảo Mật Tài Khoản:",
          text: "Bạn có trách nhiệm duy trì tính bảo mật của thông tin đăng nhập của mình. Thông báo cho chúng tôi ngay lập tức về bất kỳ truy cập trái phép nào."
        },
        {
          label: "Thông Tin Chính Xác:",
          text: "Cung cấp thông tin trung thực và đầy đủ khi tạo tài khoản của bạn và cập nhật nó."
        },
        {
          label: "Một Tài Khoản Mỗi Người Dùng:",
          text: "Không tạo nhiều tài khoản hoặc chia sẻ tài khoản với người khác."
        },
        {
          label: "Hành Động Của Bạn:",
          text: "Bạn chịu trách nhiệm cho tất cả các hoạt động xảy ra dưới tài khoản của bạn."
        }
      ]
    },
    
    acceptableUse: {
      title: "4. Chính Sách Sử Dụng Chấp Nhận Được",
      intro: "Nền tảng  được thiết kế để phục vụ Phật Pháp và giảm đau khổ. Bạn đồng ý không:",
      points: [
        "Vi phạm bất kỳ luật, quy định hoặc quyền của người khác",
        "Đăng nội dung có hại, thù hận, bạo lực hoặc khiêu dâm",
        "Quấy rối, đe dọa hoặc mạo danh người khác",
        "Phân phối thư rác, phần mềm độc hại hoặc vi-rút",
        "Cào, thu thập dữ liệu hoặc kỹ nghệ ngược nền tảng ",
        "Cố gắng giành quyền truy cập trái phép vào hệ thống hoặc dữ liệu",
        "Sử dụng nền tảng cho mục đích thương mại không liên quan đến thực hành Phật giáo hoặc hoạt động chùa chiền",
        "Trình bày sai lệch giáo lý hoặc mạo danh giáo viên tâm linh mà không có sự cho phép"
      ],
      outro: "Vi phạm chính sách này có thể dẫn đến đình chỉ hoặc chấm dứt tài khoản."
    },
    
    ai: {
      title: "5. Hướng Dẫn Sử Dụng Đại Lý AI",
      intro: "Các đại lý AI Phật giáo  là công cụ hướng dẫn, không phải là sự thay thế cho giáo viên có trình độ hoặc lời khuyên chuyên nghiệp:",
      points: [
        "Phản hồi AI được tạo ra bởi thuật toán và có thể chứa lỗi hoặc diễn giải sai",
        "Không chỉ dựa vào đại lý AI cho lời khuyên y tế, pháp lý hoặc sức khỏe tâm thần",
        "Xác minh các giáo lý quan trọng với giáo viên con người có trình độ",
        "Tôn trọng giới hạn tốc độ và tránh truy vấn lạm dụng hoặc quá mức",
        "Không sử dụng đại lý AI để tạo nội dung có hại, gian lận hoặc gây hiểu lầm"
      ]
    },
    
    ip: {
      title: "6. Sở Hữu Trí Tuệ",
      ourContent: {
        label: "Nội Dung Của Chúng Tôi:",
        text: "Tất cả mã nền tảng, thiết kế, thương hiệu, mô hình AI và tài liệu đều thuộc sở hữu của Bodhi Technology Lab hoặc người cấp phép . Bạn không được sao chép, sửa đổi hoặc phân phối tài liệu độc quyền  mà không có sự cho phép."
      },
      yourContent: {
        label: "Nội Dung Của Bạn:",
        text: "Bạn giữ quyền sở hữu nội dung bạn tải lên (tài liệu, phương tiện, dữ liệu đào tạo AI). Bằng cách tải lên, bạn cấp cho chúng tôi giấy phép xử lý, lưu trữ và hiển thị nội dung của bạn khi cần thiết để cung cấp dịch vụ ."
      },
      dharmaTeachings: {
        label: "Giáo Lý Phật Pháp:",
        text: "Các văn bản Phật giáo truyền thống, kinh sách và giáo lý được coi là một phần của di sản chung của nhân loại. Chúng tôi tôn trọng những người nắm giữ dòng truyền thừa và ghi công của tất cả các giáo lý được trình bày trên nền tảng ."
      },
      openSource: {
        label: "Mã Nguồn Mở:",
        text: "Một số thành phần của nền tảng  có thể được phát hành theo giấy phép mã nguồn mở. Các thành phần đó được điều chỉnh bởi các điều khoản giấy phép tương ứng của chúng."
      }
    },
    
    payment: {
      title: "7. Điều Khoản Thanh Toán & Quyên Góp",
      subscription: {
        label: "Gói Đăng Ký:",
        text: "Giá được liệt kê trên trang web . Phí được tính hàng tháng hoặc hàng năm trước. Chúng tôi có quyền thay đổi giá với thông báo 30 ngày."
      },
      donationProcessing: {
        label: "Xử Lý Quyên Góp:",
        text: "Đối với các nền tảng chùa chiền, chúng tôi hỗ trợ dāna (quyên góp) thay mặt bạn. Phí xử lý (Stripe, PayPal) được tiết lộ rõ ràng. Quyên góp không được hoàn lại trừ khi luật yêu cầu."
      },
      refunds: {
        label: "Hoàn Tiền:",
        text: "Phí đăng ký thường không được hoàn lại. Chúng tôi có thể cung cấp hoàn tiền theo tỷ lệ theo từng trường hợp cho việc hủy trong vòng 14 ngày kể từ khi mua ban đầu."
      },
      taxReceipts: {
        label: "Biên Lai Thuế:",
        text: "Đối với quyên góp từ thiện cho các chùa chiền đủ điều kiện, chúng tôi giúp tạo biên lai thuế theo yêu cầu của luật địa phương. Tham khảo cố vấn thuế của bạn để khấu trừ."
      }
    },
    
    termination: {
      title: "8. Chấm Dứt & Đình Chỉ",
      byYou: {
        label: "Bởi Bạn:",
        text: "Bạn có thể hủy tài khoản của mình bất cứ lúc nào thông qua cài đặt tài khoản của bạn hoặc bằng cách liên hệ với bộ phận hỗ trợ. Sau khi hủy, bạn sẽ mất quyền truy cập vào các tính năng trả phí vào cuối thời gian thanh toán của bạn."
      },
      byUs: {
        label: "Bởi Chúng Tôi:",
        text: "Chúng tôi có thể đình chỉ hoặc chấm dứt tài khoản của bạn nếu bạn vi phạm các Điều Khoản này, tham gia vào hoạt động gian lận hoặc gây ra rủi ro bảo mật. Chúng tôi sẽ cung cấp thông báo khi có thể, ngoại trừ trong trường hợp vi phạm nghiêm trọng."
      },
      dataRetention: {
        label: "Lưu Giữ Dữ Liệu:",
        text: "Sau khi chấm dứt, chúng tôi sẽ giữ lại dữ liệu của bạn trong 30 ngày để cho phép khôi phục, sau đó xóa vĩnh viễn nó (ngoại trừ theo yêu cầu của pháp luật hoặc Chính Sách Bảo Mật )."
      }
    },
    
    disclaimers: {
      title: "9. Tuyên Bố Từ Chối & Giới Hạn",
      asIs: {
        label: "Dịch Vụ NGUYÊN TRẠNG:",
        text: "Nền tảng  được cung cấp \"nguyên trạng\" mà không có bất kỳ bảo đảm nào, rõ ràng hoặc ngụ ý. Chúng tôi không đảm bảo hoạt động liên tục, không có lỗi hoặc an toàn."
      },
      noProfessionalAdvice: {
        label: "Không Có Lời Khuyên Chuyên Nghiệp:",
        text: "Các đại lý AI và nội dung nền tảng chỉ dành cho mục đích thông tin và hướng dẫn tâm linh—không phải lời khuyên pháp lý, y tế, tài chính hoặc trị liệu."
      },
      limitationOfLiability: {
        label: "Giới Hạn Trách Nhiệm Pháp Lý:",
        text: "Ở mức độ tối đa được pháp luật cho phép, Bodhi Technology Lab không chịu trách nhiệm cho thiệt hại gián tiếp, ngẫu nhiên hoặc hậu quả. Tổng trách nhiệm pháp lý  sẽ không vượt quá phí bạn đã trả trong 12 tháng qua."
      },
      thirdPartyServices: {
        label: "Dịch Vụ Bên Thứ Ba:",
        text: "Chúng tôi tích hợp với các dịch vụ bên thứ ba (bộ xử lý thanh toán, nhà cung cấp AI). Chúng tôi không chịu trách nhiệm cho hành động, sự cố hoặc thực hành bảo mật của họ."
      }
    },
    
    indemnification: {
      title: "10. Bồi Thường",
      text: "Bạn đồng ý bồi thường và giữ cho Bodhi Technology Lab, các chi nhánh và đối tác của nó không bị thiệt hại từ bất kỳ khiếu nại, thiệt hại hoặc chi phí (bao gồm phí pháp lý) phát sinh từ việc sử dụng nền tảng của bạn, vi phạm các Điều Khoản này hoặc vi phạm quyền của bên thứ ba."
    },
    
    disputes: {
      title: "11. Giải Quyết Tranh Chấp",
      informal: {
        label: "Giải Quyết Không Chính Thức:",
        text: "Trước khi nộp khiếu nại pháp lý, vui lòng liên hệ với chúng tôi tại"
      },
      email: "privacy@boddhilab.io",
      informalOutro: "để tìm kiếm giải pháp không chính thức. Chúng tôi cam kết đối thoại thiện chí.",
      arbitration: {
        label: "Trọng Tài:",
        text: "Bất kỳ tranh chấp nào không được giải quyết không chính thức sẽ được giải quyết thông qua trọng tài ràng buộc theo các quy tắc của cơ quan trọng tài được công nhận, thay vì tại tòa án."
      },
      governingLaw: {
        label: "Luật Điều Chỉnh:",
        text: "Các Điều Khoản này được điều chỉnh bởi luật pháp của khu vực pháp lý nơi Bodhi Technology Lab được đăng ký, không quan tâm đến các nguyên tắc xung đột luật pháp."
      }
    },
    
    changes: {
      title: "12. Thay Đổi Điều Khoản",
      text: "Chúng tôi có thể cập nhật các Điều Khoản này theo thời gian. Các thay đổi quan trọng sẽ được thông báo qua email và/hoặc thông báo nền tảng. Tiếp tục sử dụng sau khi thay đổi cho thấy sự chấp nhận. Nếu bạn không đồng ý với các thay đổi, bạn có thể chấm dứt tài khoản của mình."
    },
    
    miscellaneous: {
      title: "13. Khác",
      points: [
        {
          label: "Thỏa Thuận Toàn Bộ:",
          text: "Các Điều Khoản này, cùng với Chính Sách Bảo Mật , cấu thành toàn bộ thỏa thuận giữa bạn và Bodhi Technology Lab."
        },
        {
          label: "Tính Khả Thi:",
          text: "Nếu bất kỳ điều khoản nào được tìm thấy là không hợp lệ, các điều khoản còn lại vẫn có hiệu lực."
        },
        {
          label: "Từ Bỏ:",
          text: "Không thực thi bất kỳ quyền hoặc điều khoản nào không cấu thành sự từ bỏ việc thực thi trong tương lai."
        },
        {
          label: "Chuyển Nhượng:",
          text: "Bạn không được chuyển quyền của bạn theo các Điều Khoản này mà không có sự đồng ý . Chúng tôi có thể chuyển quyền  cho các chi nhánh hoặc người kế nhiệm."
        }
      ]
    },
    
    contact: {
      title: "Câu Hỏi Về Các Điều Khoản Này?",
      subtitle: "Nếu bạn có câu hỏi hoặc cần làm rõ về các Điều Khoản Dịch Vụ này, chúng tôi ở đây để giúp đỡ.",
      email: "privacy@boddhilab.io",
      company: "Bodhi Technology Lab",
      tagline: "Xây dựng công nghệ cho sự giác ngộ, với tính toàn vẹn và minh bạch"
    },
    
    footer: {
      copyright: "© 2025 Bodhi Technology Lab. Xây dựng công nghệ cho sự giác ngộ.",
      career: "Nghề Nghiệp",
      privacy: "Bảo Mật",
      terms: "Điều Khoản"
    }
  }
};
